spring:
  cloud:
    streamapp:
      security:
        enabled: false
    stream:
      bindings:
        output:
          destination: foobar
      kafka:
        bindings:
          output:
            producer:
              sync: true

logging:
  level:
    com.github.wpik: debug
